# Generated by Django 5.2.4 on 2025-11-15 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
