# Generated by Django 5.2.4 on 2025-12-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='password',
        ),
    ]
