# Generated by Django 5.2.4 on 2025-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_loginuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
